artist1 = Artist.create!( {name: "Bob Dylan"} )
artist2 = Artist.create!( {name: "Craig David"} )
artist3 = Artist.create!( {name: "Tupac"} )
artist4 = Artist.create!( {name: "Bob Marley"} )
artist5 = Artist.create!( {name: "Allen Rayman"} )
artist6 = Artist.create!( {name: "Charles Bradley"} )
artist7 = Artist.create!( {name: "David Bowie"} )
artist8 = Artist.create!( {name: "Jim Morrissey"} )
